version: "3.9"
services:
  web:
    build: ./
    container_name: django_web
    expose:
      - "8000"
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ./movies_admin/media:/opt/app/media
      - ./movies_admin/static:/opt/app/static
    env_file:
      - ./.env.prod
    networks:
      - special_network

  db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - ./.env.prod
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - special_network

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    volumes:
      - ./movies_admin/media:/var/www/media
      - ./movies_admin/static:/var/www/static
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./configs:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - special_network

  elasticsearch:
    build: ./etl
    container_name: elasticsearch
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
    - special_network
    ports:
      - "9200:9200"

  redis_state:
    image: redis:latest
    container_name: redis 
    volumes:
      - redis_data:/data
    networks:
      - special_network

networks:
  special_network:
    driver: bridge

volumes:
  pgdata:
  esdata:
  redis_data:
